### ISSUE TITLE
Publish joint names/positions will turn off

### ISSUE THREAD

**Issue by nag92** [WPI-AIM/ambf#10] opened 2019-04-27 20:17 UTC
ObjectCmd seems to default the publish the names/positions to "OFF"
so if I send a cmd to the model without always turning the fields to on I stop getting joint
data. 

I think that the default values should be turned on or maybe should be a service request.

**Comment by adnanmunawar** [comment] 2019-04-27 21:05
Good catch. Although I was testing it yesterday and I think the message shouldn’t default back once you stop publishing to it and stay to the last set value. I ll test this again just to be sure

**Comment by adnanmunawar** [comment] 2019-05-01 17:45
So based on the latest tests, the relevant afObject stops publishing the joint names/positions and children names if set to false in the Command message and not automatically. This is intended behavior and hence closing this issue

**Closed by adnanmunawar** 2019-05-01 17:45 UTC
